"""removed location, only providng in one state for now

Revision ID: 300204f102b6
Revises: b474137da725
Create Date: 2024-03-31 18:15:15.589753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '300204f102b6'
down_revision = 'b474137da725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
