"""empty message

Revision ID: 4a153b94f1f6
Revises: 7233484a72a2
Create Date: 2024-04-22 10:32:18.571086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a153b94f1f6'
down_revision = '7233484a72a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_sub')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sub',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('sub_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['sub_id'], ['subscriptions.id'], name='fk_user_sub_sub_id_subscriptions'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_sub_user_id_users'),
    sa.PrimaryKeyConstraint('user_id', 'sub_id')
    )
    # ### end Alembic commands ###
