"""small changes to relationship

Revision ID: 7233484a72a2
Revises: b27880e9e05b
Create Date: 2024-04-22 10:30:26.041435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7233484a72a2'
down_revision = 'b27880e9e05b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sub',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sub_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sub_id'], ['subscriptions.id'], name=op.f('fk_user_sub_sub_id_subscriptions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sub_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'sub_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_sub')
    # ### end Alembic commands ###
