"""added relationship to users table

Revision ID: b27880e9e05b
Revises: 6775b793aec9
Create Date: 2024-04-10 16:29:27.717115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27880e9e05b'
down_revision = '6775b793aec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_assigned_employees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_assigned_employees',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='fk_user_assigned_employees_employee_id_employees'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_assigned_employees_user_id_users'),
    sa.PrimaryKeyConstraint('user_id', 'employee_id')
    )
    # ### end Alembic commands ###
